---

- hosts: TestServers
  gather_facts: yes
  become: true

  vars_files:
    - '.passvars.yml'

  vars:
        ansible_become_pass: "{{ sudopassword }}"

  tasks:
    - name: apt update
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

    - name: download puppet
      get_url: url=https://apt.puppetlabs.com/puppet6-release-bionic.deb dest=/opt/puppet6-release-bionic.deb
    
    - name: install puppet 6
      command: dpkg -i puppet6-release-bionic.deb
      args:
        chdir: /opt

    - name: install puppet agent
      apt: name=puppet-agent update_cache=yes force_apt_get=yes

    - name: configue puppet 1
      command: echo "cetname=puppet-agent" >> /etc/puppetlabs/puppet/puppet.

    - name: configue puppet 2
      command: echo "server=puppet" >> /etc/puppetlabs/puppet/puppet.conf

    - name: configue puppet 3
      command: echo "environment=production" >> /etc/puppetlabs/puppet/puppet.conf

    - name: configue puppet 4
      command: echo "runinterval=2m" >> /etc/puppetlabs/puppet/puppet.conf

    - name: update hosts file
      lineinfile:
        dest: "/etc/hosts"
        state: present
        line: '{{server_ip}} puppet' 

    - name: run puppet agent
      command: /opt/puppetlabs/bin/puppet resource service puppet ensure=running enable=true

    - name: update path variable
      lineinfile:
        dest: "/etc/environment"
        state: present
        regexp: '^(PATH=\")({{ puppet_path }}:)?((?(2).*?(?!(?:.\"))|.*?(?!(?:{{ puppet_path }}))))(:{{ puppet_path }})?((?(4).*|\"))'
        line: '\1\3:{{ puppet_path }}\5'
        backrefs: yes

#chromium and git installation
    - name: Add chrominm Repository
      apt_repository:
        repo: ppa:canonical-chromium-builds/stage
        state: present
#install chromium web browser
    - name: Update apt and install chromium browser
      apt: update_cache=yes name=chromium-browser state=latest
#install git
    - name: install git
      apt: name=git update_cache=yes force_apt_get=yes
# install chromium webdriver
    - name: Update apt and install chromium webdriver
      apt: update_cache=yes name=chromium-chromedriver state=latest

# run connect slave node to jenkins
    - name: Change the working directory to /home/edureka/ before executing the command
      ansible.builtin.shell: connect_to_jenkins_master.sh
      args:
        chdir: /home/edureka/



