---

- hosts: master

  become: false

  tasks:

    - name: test docker website
      command: java -jar /home/edureka/edurekalabtest-0.0.1-SNAPSHOT-jar-with-dependencies.jar
      register: output
      
    - debug: var=output