---

- hosts: master

  become: true

  vars_files:
    - '.passvars.yml'

  vars:
        ansible_become_pass: "{{ sudopassword }}"

  tasks:

    - name: list certificat
      command: /opt/puppetlabs/bin/puppetserver ca list
      register: output
      
    - debug: var=output

    - name: Validate puppet agent certificat
      command: /opt/puppetlabs/bin/puppetserver ca sign --all