---

- hosts: master

  become: true

  vars_files:
    - '.passvars.yml'

  vars:
        ansible_become_pass: "{{ sudopassword }}"

  tasks:
  
    - name: check if there are any certificat
      command: /opt/puppetlabs/bin/puppetserver ca list
      wait_for:
          - "stderr_lines neq ''"

    - name: Validate puppet agent certificat
      command: /opt/puppetlabs/bin/puppetserver ca sign --all